### ISSUE TITLE
make: *** No targets specified and no makefile found

### ISSUE THREAD

**Issue by kylemcdonald** [bakercp/ofxCereal#1]
It looks like there's no makefile in the example right now.

Also: there's a formula, but I don't know what to do with it 😭 you included these helpful bootstrap.sh files everywhere else :)

**Comment by bakercp** [comment]
This addon is kind of an 80% uploaded mess.  I'll fix it up.

**Comment by bakercp** [comment]
This should be fixed now.  the boostrap.sh is optional here because I'm already including the headers.  running bootstrap will just download and copy them again.
